// Code generated by go-swagger; DO NOT EDIT.

package contact_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// NewContactCreateParams creates a new ContactCreateParams object
// with the default values initialized.
func NewContactCreateParams() *ContactCreateParams {
	var ()
	return &ContactCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContactCreateParamsWithTimeout creates a new ContactCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContactCreateParamsWithTimeout(timeout time.Duration) *ContactCreateParams {
	var ()
	return &ContactCreateParams{

		timeout: timeout,
	}
}

// NewContactCreateParamsWithContext creates a new ContactCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewContactCreateParamsWithContext(ctx context.Context) *ContactCreateParams {
	var ()
	return &ContactCreateParams{

		Context: ctx,
	}
}

// NewContactCreateParamsWithHTTPClient creates a new ContactCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContactCreateParamsWithHTTPClient(client *http.Client) *ContactCreateParams {
	var ()
	return &ContactCreateParams{
		HTTPClient: client,
	}
}

/*ContactCreateParams contains all the parameters to send to the API endpoint
for the contact create operation typically these are written to a http.Request
*/
type ContactCreateParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Contact*/
	Contact *models.Contact

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the contact create params
func (o *ContactCreateParams) WithTimeout(timeout time.Duration) *ContactCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contact create params
func (o *ContactCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contact create params
func (o *ContactCreateParams) WithContext(ctx context.Context) *ContactCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contact create params
func (o *ContactCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contact create params
func (o *ContactCreateParams) WithHTTPClient(client *http.Client) *ContactCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contact create params
func (o *ContactCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the contact create params
func (o *ContactCreateParams) WithXDomainrobotContext(xDomainrobotContext *string) *ContactCreateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the contact create params
func (o *ContactCreateParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the contact create params
func (o *ContactCreateParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *ContactCreateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the contact create params
func (o *ContactCreateParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the contact create params
func (o *ContactCreateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *ContactCreateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the contact create params
func (o *ContactCreateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the contact create params
func (o *ContactCreateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *ContactCreateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the contact create params
func (o *ContactCreateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the contact create params
func (o *ContactCreateParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *ContactCreateParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the contact create params
func (o *ContactCreateParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the contact create params
func (o *ContactCreateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *ContactCreateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the contact create params
func (o *ContactCreateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the contact create params
func (o *ContactCreateParams) WithXDomainrobotWS(xDomainrobotWS *string) *ContactCreateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the contact create params
func (o *ContactCreateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithContact adds the contact to the contact create params
func (o *ContactCreateParams) WithContact(contact *models.Contact) *ContactCreateParams {
	o.SetContact(contact)
	return o
}

// SetContact adds the contact to the contact create params
func (o *ContactCreateParams) SetContact(contact *models.Contact) {
	o.Contact = contact
}

// WriteToRequest writes these params to a swagger request
func (o *ContactCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Contact != nil {
		if err := r.SetBodyParam(o.Contact); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
