// Code generated by go-swagger; DO NOT EDIT.

package ssl_contact_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// NewSslContactUpdateParams creates a new SslContactUpdateParams object
// with the default values initialized.
func NewSslContactUpdateParams() *SslContactUpdateParams {
	var ()
	return &SslContactUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSslContactUpdateParamsWithTimeout creates a new SslContactUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSslContactUpdateParamsWithTimeout(timeout time.Duration) *SslContactUpdateParams {
	var ()
	return &SslContactUpdateParams{

		timeout: timeout,
	}
}

// NewSslContactUpdateParamsWithContext creates a new SslContactUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewSslContactUpdateParamsWithContext(ctx context.Context) *SslContactUpdateParams {
	var ()
	return &SslContactUpdateParams{

		Context: ctx,
	}
}

// NewSslContactUpdateParamsWithHTTPClient creates a new SslContactUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSslContactUpdateParamsWithHTTPClient(client *http.Client) *SslContactUpdateParams {
	var ()
	return &SslContactUpdateParams{
		HTTPClient: client,
	}
}

/*SslContactUpdateParams contains all the parameters to send to the API endpoint
for the ssl contact update operation typically these are written to a http.Request
*/
type SslContactUpdateParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Body
	  sslcontact

	*/
	Body *models.SslContact
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ssl contact update params
func (o *SslContactUpdateParams) WithTimeout(timeout time.Duration) *SslContactUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ssl contact update params
func (o *SslContactUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ssl contact update params
func (o *SslContactUpdateParams) WithContext(ctx context.Context) *SslContactUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ssl contact update params
func (o *SslContactUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ssl contact update params
func (o *SslContactUpdateParams) WithHTTPClient(client *http.Client) *SslContactUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ssl contact update params
func (o *SslContactUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the ssl contact update params
func (o *SslContactUpdateParams) WithXDomainrobotContext(xDomainrobotContext *string) *SslContactUpdateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the ssl contact update params
func (o *SslContactUpdateParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the ssl contact update params
func (o *SslContactUpdateParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *SslContactUpdateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the ssl contact update params
func (o *SslContactUpdateParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the ssl contact update params
func (o *SslContactUpdateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *SslContactUpdateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the ssl contact update params
func (o *SslContactUpdateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the ssl contact update params
func (o *SslContactUpdateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *SslContactUpdateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the ssl contact update params
func (o *SslContactUpdateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the ssl contact update params
func (o *SslContactUpdateParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *SslContactUpdateParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the ssl contact update params
func (o *SslContactUpdateParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the ssl contact update params
func (o *SslContactUpdateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *SslContactUpdateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the ssl contact update params
func (o *SslContactUpdateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the ssl contact update params
func (o *SslContactUpdateParams) WithXDomainrobotWS(xDomainrobotWS *string) *SslContactUpdateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the ssl contact update params
func (o *SslContactUpdateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the ssl contact update params
func (o *SslContactUpdateParams) WithBody(body *models.SslContact) *SslContactUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ssl contact update params
func (o *SslContactUpdateParams) SetBody(body *models.SslContact) {
	o.Body = body
}

// WithID adds the id to the ssl contact update params
func (o *SslContactUpdateParams) WithID(id int32) *SslContactUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ssl contact update params
func (o *SslContactUpdateParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SslContactUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
