// Code generated by go-swagger; DO NOT EDIT.

package id4me_agent_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteId4MeAgentParams creates a new DeleteId4MeAgentParams object
// with the default values initialized.
func NewDeleteId4MeAgentParams() *DeleteId4MeAgentParams {
	var ()
	return &DeleteId4MeAgentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteId4MeAgentParamsWithTimeout creates a new DeleteId4MeAgentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteId4MeAgentParamsWithTimeout(timeout time.Duration) *DeleteId4MeAgentParams {
	var ()
	return &DeleteId4MeAgentParams{

		timeout: timeout,
	}
}

// NewDeleteId4MeAgentParamsWithContext creates a new DeleteId4MeAgentParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteId4MeAgentParamsWithContext(ctx context.Context) *DeleteId4MeAgentParams {
	var ()
	return &DeleteId4MeAgentParams{

		Context: ctx,
	}
}

// NewDeleteId4MeAgentParamsWithHTTPClient creates a new DeleteId4MeAgentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteId4MeAgentParamsWithHTTPClient(client *http.Client) *DeleteId4MeAgentParams {
	var ()
	return &DeleteId4MeAgentParams{
		HTTPClient: client,
	}
}

/*DeleteId4MeAgentParams contains all the parameters to send to the API endpoint
for the delete id4 me agent operation typically these are written to a http.Request
*/
type DeleteId4MeAgentParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithTimeout(timeout time.Duration) *DeleteId4MeAgentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithContext(ctx context.Context) *DeleteId4MeAgentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithHTTPClient(client *http.Client) *DeleteId4MeAgentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithXDomainrobotContext(xDomainrobotContext *string) *DeleteId4MeAgentParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *DeleteId4MeAgentParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *DeleteId4MeAgentParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *DeleteId4MeAgentParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *DeleteId4MeAgentParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *DeleteId4MeAgentParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithXDomainrobotWS(xDomainrobotWS *string) *DeleteId4MeAgentParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithName adds the name to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) WithName(name string) *DeleteId4MeAgentParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete id4 me agent params
func (o *DeleteId4MeAgentParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteId4MeAgentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
