// Code generated by go-swagger; DO NOT EDIT.

package id4me_agent_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// NewId4MeAgentListParams creates a new Id4MeAgentListParams object
// with the default values initialized.
func NewId4MeAgentListParams() *Id4MeAgentListParams {
	var ()
	return &Id4MeAgentListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewId4MeAgentListParamsWithTimeout creates a new Id4MeAgentListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewId4MeAgentListParamsWithTimeout(timeout time.Duration) *Id4MeAgentListParams {
	var ()
	return &Id4MeAgentListParams{

		timeout: timeout,
	}
}

// NewId4MeAgentListParamsWithContext creates a new Id4MeAgentListParams object
// with the default values initialized, and the ability to set a context for a request
func NewId4MeAgentListParamsWithContext(ctx context.Context) *Id4MeAgentListParams {
	var ()
	return &Id4MeAgentListParams{

		Context: ctx,
	}
}

// NewId4MeAgentListParamsWithHTTPClient creates a new Id4MeAgentListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewId4MeAgentListParamsWithHTTPClient(client *http.Client) *Id4MeAgentListParams {
	var ()
	return &Id4MeAgentListParams{
		HTTPClient: client,
	}
}

/*Id4MeAgentListParams contains all the parameters to send to the API endpoint
for the id4 me agent list operation typically these are written to a http.Request
*/
type Id4MeAgentListParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Body
	  query

	*/
	Body *models.Query

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the id4 me agent list params
func (o *Id4MeAgentListParams) WithTimeout(timeout time.Duration) *Id4MeAgentListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the id4 me agent list params
func (o *Id4MeAgentListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the id4 me agent list params
func (o *Id4MeAgentListParams) WithContext(ctx context.Context) *Id4MeAgentListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the id4 me agent list params
func (o *Id4MeAgentListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the id4 me agent list params
func (o *Id4MeAgentListParams) WithHTTPClient(client *http.Client) *Id4MeAgentListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the id4 me agent list params
func (o *Id4MeAgentListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the id4 me agent list params
func (o *Id4MeAgentListParams) WithXDomainrobotContext(xDomainrobotContext *string) *Id4MeAgentListParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the id4 me agent list params
func (o *Id4MeAgentListParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the id4 me agent list params
func (o *Id4MeAgentListParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *Id4MeAgentListParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the id4 me agent list params
func (o *Id4MeAgentListParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the id4 me agent list params
func (o *Id4MeAgentListParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *Id4MeAgentListParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the id4 me agent list params
func (o *Id4MeAgentListParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the id4 me agent list params
func (o *Id4MeAgentListParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *Id4MeAgentListParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the id4 me agent list params
func (o *Id4MeAgentListParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the id4 me agent list params
func (o *Id4MeAgentListParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *Id4MeAgentListParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the id4 me agent list params
func (o *Id4MeAgentListParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the id4 me agent list params
func (o *Id4MeAgentListParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *Id4MeAgentListParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the id4 me agent list params
func (o *Id4MeAgentListParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the id4 me agent list params
func (o *Id4MeAgentListParams) WithXDomainrobotWS(xDomainrobotWS *string) *Id4MeAgentListParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the id4 me agent list params
func (o *Id4MeAgentListParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the id4 me agent list params
func (o *Id4MeAgentListParams) WithBody(body *models.Query) *Id4MeAgentListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the id4 me agent list params
func (o *Id4MeAgentListParams) SetBody(body *models.Query) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *Id4MeAgentListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
