// Code generated by go-swagger; DO NOT EDIT.

package invoice_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new invoice tasks API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for invoice tasks API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
InvoiceList lists invoice

Inquire a list of invoices with certain details. The data to be displayed can be extended per url paremeter.
*/
func (a *Client) InvoiceList(params *InvoiceListParams) (*InvoiceListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewInvoiceListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "InvoiceList",
		Method:             "POST",
		PathPattern:        "/invoice/_search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &InvoiceListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*InvoiceListOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
