// Code generated by go-swagger; DO NOT EDIT.

package domain_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDomainAuthinfo1DeleteParams creates a new DomainAuthinfo1DeleteParams object
// with the default values initialized.
func NewDomainAuthinfo1DeleteParams() *DomainAuthinfo1DeleteParams {
	var ()
	return &DomainAuthinfo1DeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDomainAuthinfo1DeleteParamsWithTimeout creates a new DomainAuthinfo1DeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDomainAuthinfo1DeleteParamsWithTimeout(timeout time.Duration) *DomainAuthinfo1DeleteParams {
	var ()
	return &DomainAuthinfo1DeleteParams{

		timeout: timeout,
	}
}

// NewDomainAuthinfo1DeleteParamsWithContext creates a new DomainAuthinfo1DeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewDomainAuthinfo1DeleteParamsWithContext(ctx context.Context) *DomainAuthinfo1DeleteParams {
	var ()
	return &DomainAuthinfo1DeleteParams{

		Context: ctx,
	}
}

// NewDomainAuthinfo1DeleteParamsWithHTTPClient creates a new DomainAuthinfo1DeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDomainAuthinfo1DeleteParamsWithHTTPClient(client *http.Client) *DomainAuthinfo1DeleteParams {
	var ()
	return &DomainAuthinfo1DeleteParams{
		HTTPClient: client,
	}
}

/*DomainAuthinfo1DeleteParams contains all the parameters to send to the API endpoint
for the domain authinfo1 delete operation typically these are written to a http.Request
*/
type DomainAuthinfo1DeleteParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithTimeout(timeout time.Duration) *DomainAuthinfo1DeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithContext(ctx context.Context) *DomainAuthinfo1DeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithHTTPClient(client *http.Client) *DomainAuthinfo1DeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithXDomainrobotContext(xDomainrobotContext *string) *DomainAuthinfo1DeleteParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *DomainAuthinfo1DeleteParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *DomainAuthinfo1DeleteParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *DomainAuthinfo1DeleteParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *DomainAuthinfo1DeleteParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *DomainAuthinfo1DeleteParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithXDomainrobotWS(xDomainrobotWS *string) *DomainAuthinfo1DeleteParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithName adds the name to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) WithName(name string) *DomainAuthinfo1DeleteParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the domain authinfo1 delete params
func (o *DomainAuthinfo1DeleteParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DomainAuthinfo1DeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
