// Code generated by go-swagger; DO NOT EDIT.

package domain_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// NewDomainCancelationCreateParams creates a new DomainCancelationCreateParams object
// with the default values initialized.
func NewDomainCancelationCreateParams() *DomainCancelationCreateParams {
	var ()
	return &DomainCancelationCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDomainCancelationCreateParamsWithTimeout creates a new DomainCancelationCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDomainCancelationCreateParamsWithTimeout(timeout time.Duration) *DomainCancelationCreateParams {
	var ()
	return &DomainCancelationCreateParams{

		timeout: timeout,
	}
}

// NewDomainCancelationCreateParamsWithContext creates a new DomainCancelationCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDomainCancelationCreateParamsWithContext(ctx context.Context) *DomainCancelationCreateParams {
	var ()
	return &DomainCancelationCreateParams{

		Context: ctx,
	}
}

// NewDomainCancelationCreateParamsWithHTTPClient creates a new DomainCancelationCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDomainCancelationCreateParamsWithHTTPClient(client *http.Client) *DomainCancelationCreateParams {
	var ()
	return &DomainCancelationCreateParams{
		HTTPClient: client,
	}
}

/*DomainCancelationCreateParams contains all the parameters to send to the API endpoint
for the domain cancelation create operation typically these are written to a http.Request
*/
type DomainCancelationCreateParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Body
	  domain

	*/
	Body *models.DomainCancelation

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithTimeout(timeout time.Duration) *DomainCancelationCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithContext(ctx context.Context) *DomainCancelationCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithHTTPClient(client *http.Client) *DomainCancelationCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotContext(xDomainrobotContext *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotWS(xDomainrobotWS *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithBody(body *models.DomainCancelation) *DomainCancelationCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetBody(body *models.DomainCancelation) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DomainCancelationCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
