// Code generated by go-swagger; DO NOT EDIT.

package domain_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// NewDomainCreateParams creates a new DomainCreateParams object
// with the default values initialized.
func NewDomainCreateParams() *DomainCreateParams {
	var ()
	return &DomainCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDomainCreateParamsWithTimeout creates a new DomainCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDomainCreateParamsWithTimeout(timeout time.Duration) *DomainCreateParams {
	var ()
	return &DomainCreateParams{

		timeout: timeout,
	}
}

// NewDomainCreateParamsWithContext creates a new DomainCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDomainCreateParamsWithContext(ctx context.Context) *DomainCreateParams {
	var ()
	return &DomainCreateParams{

		Context: ctx,
	}
}

// NewDomainCreateParamsWithHTTPClient creates a new DomainCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDomainCreateParamsWithHTTPClient(client *http.Client) *DomainCreateParams {
	var ()
	return &DomainCreateParams{
		HTTPClient: client,
	}
}

/*DomainCreateParams contains all the parameters to send to the API endpoint
for the domain create operation typically these are written to a http.Request
*/
type DomainCreateParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Body
	  domain

	*/
	Body *models.Domain

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the domain create params
func (o *DomainCreateParams) WithTimeout(timeout time.Duration) *DomainCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the domain create params
func (o *DomainCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the domain create params
func (o *DomainCreateParams) WithContext(ctx context.Context) *DomainCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the domain create params
func (o *DomainCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the domain create params
func (o *DomainCreateParams) WithHTTPClient(client *http.Client) *DomainCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the domain create params
func (o *DomainCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the domain create params
func (o *DomainCreateParams) WithXDomainrobotContext(xDomainrobotContext *string) *DomainCreateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the domain create params
func (o *DomainCreateParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the domain create params
func (o *DomainCreateParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *DomainCreateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the domain create params
func (o *DomainCreateParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the domain create params
func (o *DomainCreateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *DomainCreateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the domain create params
func (o *DomainCreateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the domain create params
func (o *DomainCreateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *DomainCreateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the domain create params
func (o *DomainCreateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the domain create params
func (o *DomainCreateParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *DomainCreateParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the domain create params
func (o *DomainCreateParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the domain create params
func (o *DomainCreateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *DomainCreateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the domain create params
func (o *DomainCreateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the domain create params
func (o *DomainCreateParams) WithXDomainrobotWS(xDomainrobotWS *string) *DomainCreateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the domain create params
func (o *DomainCreateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the domain create params
func (o *DomainCreateParams) WithBody(body *models.Domain) *DomainCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the domain create params
func (o *DomainCreateParams) SetBody(body *models.Domain) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DomainCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
