// Code generated by go-swagger; DO NOT EDIT.

package job_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewJobInfoParams creates a new JobInfoParams object
// with the default values initialized.
func NewJobInfoParams() *JobInfoParams {
	var ()
	return &JobInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJobInfoParamsWithTimeout creates a new JobInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJobInfoParamsWithTimeout(timeout time.Duration) *JobInfoParams {
	var ()
	return &JobInfoParams{

		timeout: timeout,
	}
}

// NewJobInfoParamsWithContext creates a new JobInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewJobInfoParamsWithContext(ctx context.Context) *JobInfoParams {
	var ()
	return &JobInfoParams{

		Context: ctx,
	}
}

// NewJobInfoParamsWithHTTPClient creates a new JobInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJobInfoParamsWithHTTPClient(client *http.Client) *JobInfoParams {
	var ()
	return &JobInfoParams{
		HTTPClient: client,
	}
}

/*JobInfoParams contains all the parameters to send to the API endpoint
for the job info operation typically these are written to a http.Request
*/
type JobInfoParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the job info params
func (o *JobInfoParams) WithTimeout(timeout time.Duration) *JobInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the job info params
func (o *JobInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the job info params
func (o *JobInfoParams) WithContext(ctx context.Context) *JobInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the job info params
func (o *JobInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the job info params
func (o *JobInfoParams) WithHTTPClient(client *http.Client) *JobInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the job info params
func (o *JobInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the job info params
func (o *JobInfoParams) WithXDomainrobotContext(xDomainrobotContext *string) *JobInfoParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the job info params
func (o *JobInfoParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the job info params
func (o *JobInfoParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *JobInfoParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the job info params
func (o *JobInfoParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the job info params
func (o *JobInfoParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *JobInfoParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the job info params
func (o *JobInfoParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the job info params
func (o *JobInfoParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *JobInfoParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the job info params
func (o *JobInfoParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the job info params
func (o *JobInfoParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *JobInfoParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the job info params
func (o *JobInfoParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the job info params
func (o *JobInfoParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *JobInfoParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the job info params
func (o *JobInfoParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the job info params
func (o *JobInfoParams) WithXDomainrobotWS(xDomainrobotWS *string) *JobInfoParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the job info params
func (o *JobInfoParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithID adds the id to the job info params
func (o *JobInfoParams) WithID(id int32) *JobInfoParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the job info params
func (o *JobInfoParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *JobInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
