// Code generated by go-swagger; DO NOT EDIT.

package whois_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// DomainWhoisReader is a Reader for the DomainWhois structure.
type DomainWhoisReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DomainWhoisReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDomainWhoisOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDomainWhoisOK creates a DomainWhoisOK with default headers values
func NewDomainWhoisOK() *DomainWhoisOK {
	return &DomainWhoisOK{}
}

/*DomainWhoisOK handles this case with default header values.

successful operation
*/
type DomainWhoisOK struct {
	Payload *models.JSONResponseDataDomain
}

func (o *DomainWhoisOK) Error() string {
	return fmt.Sprintf("[GET /domain/{name}/_whois][%d] domainWhoisOK  %+v", 200, o.Payload)
}

func (o *DomainWhoisOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataDomain)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
