// Code generated by go-swagger; DO NOT EDIT.

package whois_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new whois tasks API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for whois tasks API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DomainWhois whois tasks

Fetches the whois data of a domain from registry with optional data parsing.
*/
func (a *Client) DomainWhois(params *DomainWhoisParams) (*DomainWhoisOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDomainWhoisParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DomainWhois",
		Method:             "GET",
		PathPattern:        "/domain/{name}/_whois",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DomainWhoisReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DomainWhoisOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
