// Code generated by go-swagger; DO NOT EDIT.

package zone_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewZoneDeleteParams creates a new ZoneDeleteParams object
// with the default values initialized.
func NewZoneDeleteParams() *ZoneDeleteParams {
	var ()
	return &ZoneDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewZoneDeleteParamsWithTimeout creates a new ZoneDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewZoneDeleteParamsWithTimeout(timeout time.Duration) *ZoneDeleteParams {
	var ()
	return &ZoneDeleteParams{

		timeout: timeout,
	}
}

// NewZoneDeleteParamsWithContext creates a new ZoneDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewZoneDeleteParamsWithContext(ctx context.Context) *ZoneDeleteParams {
	var ()
	return &ZoneDeleteParams{

		Context: ctx,
	}
}

// NewZoneDeleteParamsWithHTTPClient creates a new ZoneDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewZoneDeleteParamsWithHTTPClient(client *http.Client) *ZoneDeleteParams {
	var ()
	return &ZoneDeleteParams{
		HTTPClient: client,
	}
}

/*ZoneDeleteParams contains all the parameters to send to the API endpoint
for the zone delete operation typically these are written to a http.Request
*/
type ZoneDeleteParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Name*/
	Name string
	/*Nameserver*/
	Nameserver string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the zone delete params
func (o *ZoneDeleteParams) WithTimeout(timeout time.Duration) *ZoneDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the zone delete params
func (o *ZoneDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the zone delete params
func (o *ZoneDeleteParams) WithContext(ctx context.Context) *ZoneDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the zone delete params
func (o *ZoneDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the zone delete params
func (o *ZoneDeleteParams) WithHTTPClient(client *http.Client) *ZoneDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the zone delete params
func (o *ZoneDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the zone delete params
func (o *ZoneDeleteParams) WithXDomainrobotContext(xDomainrobotContext *string) *ZoneDeleteParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the zone delete params
func (o *ZoneDeleteParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the zone delete params
func (o *ZoneDeleteParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *ZoneDeleteParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the zone delete params
func (o *ZoneDeleteParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the zone delete params
func (o *ZoneDeleteParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *ZoneDeleteParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the zone delete params
func (o *ZoneDeleteParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the zone delete params
func (o *ZoneDeleteParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *ZoneDeleteParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the zone delete params
func (o *ZoneDeleteParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the zone delete params
func (o *ZoneDeleteParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *ZoneDeleteParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the zone delete params
func (o *ZoneDeleteParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the zone delete params
func (o *ZoneDeleteParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *ZoneDeleteParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the zone delete params
func (o *ZoneDeleteParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the zone delete params
func (o *ZoneDeleteParams) WithXDomainrobotWS(xDomainrobotWS *string) *ZoneDeleteParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the zone delete params
func (o *ZoneDeleteParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithName adds the name to the zone delete params
func (o *ZoneDeleteParams) WithName(name string) *ZoneDeleteParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the zone delete params
func (o *ZoneDeleteParams) SetName(name string) {
	o.Name = name
}

// WithNameserver adds the nameserver to the zone delete params
func (o *ZoneDeleteParams) WithNameserver(nameserver string) *ZoneDeleteParams {
	o.SetNameserver(nameserver)
	return o
}

// SetNameserver adds the nameserver to the zone delete params
func (o *ZoneDeleteParams) SetNameserver(nameserver string) {
	o.Nameserver = nameserver
}

// WriteToRequest writes these params to a swagger request
func (o *ZoneDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param nameserver
	if err := r.SetPathParam("nameserver", o.Nameserver); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
