// Code generated by go-swagger; DO NOT EDIT.

package zone_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// NewZoneStreamParams creates a new ZoneStreamParams object
// with the default values initialized.
func NewZoneStreamParams() *ZoneStreamParams {
	var ()
	return &ZoneStreamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewZoneStreamParamsWithTimeout creates a new ZoneStreamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewZoneStreamParamsWithTimeout(timeout time.Duration) *ZoneStreamParams {
	var ()
	return &ZoneStreamParams{

		timeout: timeout,
	}
}

// NewZoneStreamParamsWithContext creates a new ZoneStreamParams object
// with the default values initialized, and the ability to set a context for a request
func NewZoneStreamParamsWithContext(ctx context.Context) *ZoneStreamParams {
	var ()
	return &ZoneStreamParams{

		Context: ctx,
	}
}

// NewZoneStreamParamsWithHTTPClient creates a new ZoneStreamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewZoneStreamParamsWithHTTPClient(client *http.Client) *ZoneStreamParams {
	var ()
	return &ZoneStreamParams{
		HTTPClient: client,
	}
}

/*ZoneStreamParams contains all the parameters to send to the API endpoint
for the zone stream operation typically these are written to a http.Request
*/
type ZoneStreamParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Body
	  zoneStream

	*/
	Body *models.ZoneStream
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the zone stream params
func (o *ZoneStreamParams) WithTimeout(timeout time.Duration) *ZoneStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the zone stream params
func (o *ZoneStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the zone stream params
func (o *ZoneStreamParams) WithContext(ctx context.Context) *ZoneStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the zone stream params
func (o *ZoneStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the zone stream params
func (o *ZoneStreamParams) WithHTTPClient(client *http.Client) *ZoneStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the zone stream params
func (o *ZoneStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the zone stream params
func (o *ZoneStreamParams) WithXDomainrobotContext(xDomainrobotContext *string) *ZoneStreamParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the zone stream params
func (o *ZoneStreamParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the zone stream params
func (o *ZoneStreamParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *ZoneStreamParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the zone stream params
func (o *ZoneStreamParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the zone stream params
func (o *ZoneStreamParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *ZoneStreamParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the zone stream params
func (o *ZoneStreamParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the zone stream params
func (o *ZoneStreamParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *ZoneStreamParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the zone stream params
func (o *ZoneStreamParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the zone stream params
func (o *ZoneStreamParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *ZoneStreamParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the zone stream params
func (o *ZoneStreamParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the zone stream params
func (o *ZoneStreamParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *ZoneStreamParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the zone stream params
func (o *ZoneStreamParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the zone stream params
func (o *ZoneStreamParams) WithXDomainrobotWS(xDomainrobotWS *string) *ZoneStreamParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the zone stream params
func (o *ZoneStreamParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the zone stream params
func (o *ZoneStreamParams) WithBody(body *models.ZoneStream) *ZoneStreamParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the zone stream params
func (o *ZoneStreamParams) SetBody(body *models.ZoneStream) {
	o.Body = body
}

// WithName adds the name to the zone stream params
func (o *ZoneStreamParams) WithName(name string) *ZoneStreamParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the zone stream params
func (o *ZoneStreamParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ZoneStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
