// Code generated by go-swagger; DO NOT EDIT.

package subscription_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// NewSubscriptionUpdateParams creates a new SubscriptionUpdateParams object
// with the default values initialized.
func NewSubscriptionUpdateParams() *SubscriptionUpdateParams {
	var ()
	return &SubscriptionUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSubscriptionUpdateParamsWithTimeout creates a new SubscriptionUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSubscriptionUpdateParamsWithTimeout(timeout time.Duration) *SubscriptionUpdateParams {
	var ()
	return &SubscriptionUpdateParams{

		timeout: timeout,
	}
}

// NewSubscriptionUpdateParamsWithContext creates a new SubscriptionUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewSubscriptionUpdateParamsWithContext(ctx context.Context) *SubscriptionUpdateParams {
	var ()
	return &SubscriptionUpdateParams{

		Context: ctx,
	}
}

// NewSubscriptionUpdateParamsWithHTTPClient creates a new SubscriptionUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSubscriptionUpdateParamsWithHTTPClient(client *http.Client) *SubscriptionUpdateParams {
	var ()
	return &SubscriptionUpdateParams{
		HTTPClient: client,
	}
}

/*SubscriptionUpdateParams contains all the parameters to send to the API endpoint
for the subscription update operation typically these are written to a http.Request
*/
type SubscriptionUpdateParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Body
	  subscription

	*/
	Body *models.Subscription

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the subscription update params
func (o *SubscriptionUpdateParams) WithTimeout(timeout time.Duration) *SubscriptionUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the subscription update params
func (o *SubscriptionUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the subscription update params
func (o *SubscriptionUpdateParams) WithContext(ctx context.Context) *SubscriptionUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the subscription update params
func (o *SubscriptionUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the subscription update params
func (o *SubscriptionUpdateParams) WithHTTPClient(client *http.Client) *SubscriptionUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the subscription update params
func (o *SubscriptionUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the subscription update params
func (o *SubscriptionUpdateParams) WithXDomainrobotContext(xDomainrobotContext *string) *SubscriptionUpdateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the subscription update params
func (o *SubscriptionUpdateParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the subscription update params
func (o *SubscriptionUpdateParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *SubscriptionUpdateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the subscription update params
func (o *SubscriptionUpdateParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the subscription update params
func (o *SubscriptionUpdateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *SubscriptionUpdateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the subscription update params
func (o *SubscriptionUpdateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the subscription update params
func (o *SubscriptionUpdateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *SubscriptionUpdateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the subscription update params
func (o *SubscriptionUpdateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the subscription update params
func (o *SubscriptionUpdateParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *SubscriptionUpdateParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the subscription update params
func (o *SubscriptionUpdateParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the subscription update params
func (o *SubscriptionUpdateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *SubscriptionUpdateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the subscription update params
func (o *SubscriptionUpdateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the subscription update params
func (o *SubscriptionUpdateParams) WithXDomainrobotWS(xDomainrobotWS *string) *SubscriptionUpdateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the subscription update params
func (o *SubscriptionUpdateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the subscription update params
func (o *SubscriptionUpdateParams) WithBody(body *models.Subscription) *SubscriptionUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the subscription update params
func (o *SubscriptionUpdateParams) SetBody(body *models.Subscription) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SubscriptionUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
