// Code generated by go-swagger; DO NOT EDIT.

package subscription_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// NewSubscriptionCreateParams creates a new SubscriptionCreateParams object
// with the default values initialized.
func NewSubscriptionCreateParams() *SubscriptionCreateParams {
	var ()
	return &SubscriptionCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSubscriptionCreateParamsWithTimeout creates a new SubscriptionCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSubscriptionCreateParamsWithTimeout(timeout time.Duration) *SubscriptionCreateParams {
	var ()
	return &SubscriptionCreateParams{

		timeout: timeout,
	}
}

// NewSubscriptionCreateParamsWithContext creates a new SubscriptionCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewSubscriptionCreateParamsWithContext(ctx context.Context) *SubscriptionCreateParams {
	var ()
	return &SubscriptionCreateParams{

		Context: ctx,
	}
}

// NewSubscriptionCreateParamsWithHTTPClient creates a new SubscriptionCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSubscriptionCreateParamsWithHTTPClient(client *http.Client) *SubscriptionCreateParams {
	var ()
	return &SubscriptionCreateParams{
		HTTPClient: client,
	}
}

/*SubscriptionCreateParams contains all the parameters to send to the API endpoint
for the subscription create operation typically these are written to a http.Request
*/
type SubscriptionCreateParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Subscription*/
	Subscription *models.Subscription

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the subscription create params
func (o *SubscriptionCreateParams) WithTimeout(timeout time.Duration) *SubscriptionCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the subscription create params
func (o *SubscriptionCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the subscription create params
func (o *SubscriptionCreateParams) WithContext(ctx context.Context) *SubscriptionCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the subscription create params
func (o *SubscriptionCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the subscription create params
func (o *SubscriptionCreateParams) WithHTTPClient(client *http.Client) *SubscriptionCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the subscription create params
func (o *SubscriptionCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the subscription create params
func (o *SubscriptionCreateParams) WithXDomainrobotContext(xDomainrobotContext *string) *SubscriptionCreateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the subscription create params
func (o *SubscriptionCreateParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the subscription create params
func (o *SubscriptionCreateParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *SubscriptionCreateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the subscription create params
func (o *SubscriptionCreateParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the subscription create params
func (o *SubscriptionCreateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *SubscriptionCreateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the subscription create params
func (o *SubscriptionCreateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the subscription create params
func (o *SubscriptionCreateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *SubscriptionCreateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the subscription create params
func (o *SubscriptionCreateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the subscription create params
func (o *SubscriptionCreateParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *SubscriptionCreateParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the subscription create params
func (o *SubscriptionCreateParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the subscription create params
func (o *SubscriptionCreateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *SubscriptionCreateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the subscription create params
func (o *SubscriptionCreateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the subscription create params
func (o *SubscriptionCreateParams) WithXDomainrobotWS(xDomainrobotWS *string) *SubscriptionCreateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the subscription create params
func (o *SubscriptionCreateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithSubscription adds the subscription to the subscription create params
func (o *SubscriptionCreateParams) WithSubscription(subscription *models.Subscription) *SubscriptionCreateParams {
	o.SetSubscription(subscription)
	return o
}

// SetSubscription adds the subscription to the subscription create params
func (o *SubscriptionCreateParams) SetSubscription(subscription *models.Subscription) {
	o.Subscription = subscription
}

// WriteToRequest writes these params to a swagger request
func (o *SubscriptionCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Subscription != nil {
		if err := r.SetBodyParam(o.Subscription); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
