// Code generated by go-swagger; DO NOT EDIT.

package invoice_info_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInvoiceInfoParams creates a new InvoiceInfoParams object
// with the default values initialized.
func NewInvoiceInfoParams() *InvoiceInfoParams {
	var ()
	return &InvoiceInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInvoiceInfoParamsWithTimeout creates a new InvoiceInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInvoiceInfoParamsWithTimeout(timeout time.Duration) *InvoiceInfoParams {
	var ()
	return &InvoiceInfoParams{

		timeout: timeout,
	}
}

// NewInvoiceInfoParamsWithContext creates a new InvoiceInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewInvoiceInfoParamsWithContext(ctx context.Context) *InvoiceInfoParams {
	var ()
	return &InvoiceInfoParams{

		Context: ctx,
	}
}

// NewInvoiceInfoParamsWithHTTPClient creates a new InvoiceInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInvoiceInfoParamsWithHTTPClient(client *http.Client) *InvoiceInfoParams {
	var ()
	return &InvoiceInfoParams{
		HTTPClient: client,
	}
}

/*InvoiceInfoParams contains all the parameters to send to the API endpoint
for the invoice info operation typically these are written to a http.Request
*/
type InvoiceInfoParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the invoice info params
func (o *InvoiceInfoParams) WithTimeout(timeout time.Duration) *InvoiceInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the invoice info params
func (o *InvoiceInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the invoice info params
func (o *InvoiceInfoParams) WithContext(ctx context.Context) *InvoiceInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the invoice info params
func (o *InvoiceInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the invoice info params
func (o *InvoiceInfoParams) WithHTTPClient(client *http.Client) *InvoiceInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the invoice info params
func (o *InvoiceInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the invoice info params
func (o *InvoiceInfoParams) WithXDomainrobotContext(xDomainrobotContext *string) *InvoiceInfoParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the invoice info params
func (o *InvoiceInfoParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the invoice info params
func (o *InvoiceInfoParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *InvoiceInfoParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the invoice info params
func (o *InvoiceInfoParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the invoice info params
func (o *InvoiceInfoParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *InvoiceInfoParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the invoice info params
func (o *InvoiceInfoParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the invoice info params
func (o *InvoiceInfoParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *InvoiceInfoParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the invoice info params
func (o *InvoiceInfoParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the invoice info params
func (o *InvoiceInfoParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *InvoiceInfoParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the invoice info params
func (o *InvoiceInfoParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the invoice info params
func (o *InvoiceInfoParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *InvoiceInfoParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the invoice info params
func (o *InvoiceInfoParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the invoice info params
func (o *InvoiceInfoParams) WithXDomainrobotWS(xDomainrobotWS *string) *InvoiceInfoParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the invoice info params
func (o *InvoiceInfoParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithID adds the id to the invoice info params
func (o *InvoiceInfoParams) WithID(id int64) *InvoiceInfoParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the invoice info params
func (o *InvoiceInfoParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *InvoiceInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
