// Code generated by go-swagger; DO NOT EDIT.

package user_2fa_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOtpAuthCreateParams creates a new OtpAuthCreateParams object
// with the default values initialized.
func NewOtpAuthCreateParams() *OtpAuthCreateParams {
	var ()
	return &OtpAuthCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOtpAuthCreateParamsWithTimeout creates a new OtpAuthCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOtpAuthCreateParamsWithTimeout(timeout time.Duration) *OtpAuthCreateParams {
	var ()
	return &OtpAuthCreateParams{

		timeout: timeout,
	}
}

// NewOtpAuthCreateParamsWithContext creates a new OtpAuthCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewOtpAuthCreateParamsWithContext(ctx context.Context) *OtpAuthCreateParams {
	var ()
	return &OtpAuthCreateParams{

		Context: ctx,
	}
}

// NewOtpAuthCreateParamsWithHTTPClient creates a new OtpAuthCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOtpAuthCreateParamsWithHTTPClient(client *http.Client) *OtpAuthCreateParams {
	var ()
	return &OtpAuthCreateParams{
		HTTPClient: client,
	}
}

/*OtpAuthCreateParams contains all the parameters to send to the API endpoint
for the otp auth create operation typically these are written to a http.Request
*/
type OtpAuthCreateParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the otp auth create params
func (o *OtpAuthCreateParams) WithTimeout(timeout time.Duration) *OtpAuthCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the otp auth create params
func (o *OtpAuthCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the otp auth create params
func (o *OtpAuthCreateParams) WithContext(ctx context.Context) *OtpAuthCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the otp auth create params
func (o *OtpAuthCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the otp auth create params
func (o *OtpAuthCreateParams) WithHTTPClient(client *http.Client) *OtpAuthCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the otp auth create params
func (o *OtpAuthCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the otp auth create params
func (o *OtpAuthCreateParams) WithXDomainrobotContext(xDomainrobotContext *string) *OtpAuthCreateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the otp auth create params
func (o *OtpAuthCreateParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the otp auth create params
func (o *OtpAuthCreateParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *OtpAuthCreateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the otp auth create params
func (o *OtpAuthCreateParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the otp auth create params
func (o *OtpAuthCreateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *OtpAuthCreateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the otp auth create params
func (o *OtpAuthCreateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the otp auth create params
func (o *OtpAuthCreateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *OtpAuthCreateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the otp auth create params
func (o *OtpAuthCreateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the otp auth create params
func (o *OtpAuthCreateParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *OtpAuthCreateParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the otp auth create params
func (o *OtpAuthCreateParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the otp auth create params
func (o *OtpAuthCreateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *OtpAuthCreateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the otp auth create params
func (o *OtpAuthCreateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the otp auth create params
func (o *OtpAuthCreateParams) WithXDomainrobotWS(xDomainrobotWS *string) *OtpAuthCreateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the otp auth create params
func (o *OtpAuthCreateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WriteToRequest writes these params to a swagger request
func (o *OtpAuthCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
