// Code generated by go-swagger; DO NOT EDIT.

package id4me_identity_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewConfirmId4MeIdentityParams creates a new ConfirmId4MeIdentityParams object
// with the default values initialized.
func NewConfirmId4MeIdentityParams() *ConfirmId4MeIdentityParams {
	var ()
	return &ConfirmId4MeIdentityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewConfirmId4MeIdentityParamsWithTimeout creates a new ConfirmId4MeIdentityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewConfirmId4MeIdentityParamsWithTimeout(timeout time.Duration) *ConfirmId4MeIdentityParams {
	var ()
	return &ConfirmId4MeIdentityParams{

		timeout: timeout,
	}
}

// NewConfirmId4MeIdentityParamsWithContext creates a new ConfirmId4MeIdentityParams object
// with the default values initialized, and the ability to set a context for a request
func NewConfirmId4MeIdentityParamsWithContext(ctx context.Context) *ConfirmId4MeIdentityParams {
	var ()
	return &ConfirmId4MeIdentityParams{

		Context: ctx,
	}
}

// NewConfirmId4MeIdentityParamsWithHTTPClient creates a new ConfirmId4MeIdentityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewConfirmId4MeIdentityParamsWithHTTPClient(client *http.Client) *ConfirmId4MeIdentityParams {
	var ()
	return &ConfirmId4MeIdentityParams{
		HTTPClient: client,
	}
}

/*ConfirmId4MeIdentityParams contains all the parameters to send to the API endpoint
for the confirm id4 me identity operation typically these are written to a http.Request
*/
type ConfirmId4MeIdentityParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithTimeout(timeout time.Duration) *ConfirmId4MeIdentityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithContext(ctx context.Context) *ConfirmId4MeIdentityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithHTTPClient(client *http.Client) *ConfirmId4MeIdentityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithXDomainrobotContext(xDomainrobotContext *string) *ConfirmId4MeIdentityParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *ConfirmId4MeIdentityParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *ConfirmId4MeIdentityParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *ConfirmId4MeIdentityParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *ConfirmId4MeIdentityParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *ConfirmId4MeIdentityParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithXDomainrobotWS(xDomainrobotWS *string) *ConfirmId4MeIdentityParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithName adds the name to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) WithName(name string) *ConfirmId4MeIdentityParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the confirm id4 me identity params
func (o *ConfirmId4MeIdentityParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ConfirmId4MeIdentityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
