// Code generated by go-swagger; DO NOT EDIT.

package mail_proxy_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMailProxyDeleteParams creates a new MailProxyDeleteParams object
// with the default values initialized.
func NewMailProxyDeleteParams() *MailProxyDeleteParams {
	var ()
	return &MailProxyDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMailProxyDeleteParamsWithTimeout creates a new MailProxyDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMailProxyDeleteParamsWithTimeout(timeout time.Duration) *MailProxyDeleteParams {
	var ()
	return &MailProxyDeleteParams{

		timeout: timeout,
	}
}

// NewMailProxyDeleteParamsWithContext creates a new MailProxyDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewMailProxyDeleteParamsWithContext(ctx context.Context) *MailProxyDeleteParams {
	var ()
	return &MailProxyDeleteParams{

		Context: ctx,
	}
}

// NewMailProxyDeleteParamsWithHTTPClient creates a new MailProxyDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMailProxyDeleteParamsWithHTTPClient(client *http.Client) *MailProxyDeleteParams {
	var ()
	return &MailProxyDeleteParams{
		HTTPClient: client,
	}
}

/*MailProxyDeleteParams contains all the parameters to send to the API endpoint
for the mail proxy delete operation typically these are written to a http.Request
*/
type MailProxyDeleteParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Domain*/
	Domain string
	/*Keys
	  If the dns should be provisioned if available.

	*/
	Keys []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the mail proxy delete params
func (o *MailProxyDeleteParams) WithTimeout(timeout time.Duration) *MailProxyDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mail proxy delete params
func (o *MailProxyDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mail proxy delete params
func (o *MailProxyDeleteParams) WithContext(ctx context.Context) *MailProxyDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mail proxy delete params
func (o *MailProxyDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mail proxy delete params
func (o *MailProxyDeleteParams) WithHTTPClient(client *http.Client) *MailProxyDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mail proxy delete params
func (o *MailProxyDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the mail proxy delete params
func (o *MailProxyDeleteParams) WithXDomainrobotContext(xDomainrobotContext *string) *MailProxyDeleteParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the mail proxy delete params
func (o *MailProxyDeleteParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the mail proxy delete params
func (o *MailProxyDeleteParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *MailProxyDeleteParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the mail proxy delete params
func (o *MailProxyDeleteParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the mail proxy delete params
func (o *MailProxyDeleteParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *MailProxyDeleteParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the mail proxy delete params
func (o *MailProxyDeleteParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the mail proxy delete params
func (o *MailProxyDeleteParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *MailProxyDeleteParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the mail proxy delete params
func (o *MailProxyDeleteParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the mail proxy delete params
func (o *MailProxyDeleteParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *MailProxyDeleteParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the mail proxy delete params
func (o *MailProxyDeleteParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the mail proxy delete params
func (o *MailProxyDeleteParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *MailProxyDeleteParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the mail proxy delete params
func (o *MailProxyDeleteParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the mail proxy delete params
func (o *MailProxyDeleteParams) WithXDomainrobotWS(xDomainrobotWS *string) *MailProxyDeleteParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the mail proxy delete params
func (o *MailProxyDeleteParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithDomain adds the domain to the mail proxy delete params
func (o *MailProxyDeleteParams) WithDomain(domain string) *MailProxyDeleteParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the mail proxy delete params
func (o *MailProxyDeleteParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithKeys adds the keys to the mail proxy delete params
func (o *MailProxyDeleteParams) WithKeys(keys []string) *MailProxyDeleteParams {
	o.SetKeys(keys)
	return o
}

// SetKeys adds the keys to the mail proxy delete params
func (o *MailProxyDeleteParams) SetKeys(keys []string) {
	o.Keys = keys
}

// WriteToRequest writes these params to a swagger request
func (o *MailProxyDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	valuesKeys := o.Keys

	joinedKeys := swag.JoinByFormat(valuesKeys, "multi")
	// query array param keys
	if err := r.SetQueryParam("keys", joinedKeys...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
