// Code generated by go-swagger; DO NOT EDIT.

package mail_proxy_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMailProxyInfoParams creates a new MailProxyInfoParams object
// with the default values initialized.
func NewMailProxyInfoParams() *MailProxyInfoParams {
	var ()
	return &MailProxyInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMailProxyInfoParamsWithTimeout creates a new MailProxyInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMailProxyInfoParamsWithTimeout(timeout time.Duration) *MailProxyInfoParams {
	var ()
	return &MailProxyInfoParams{

		timeout: timeout,
	}
}

// NewMailProxyInfoParamsWithContext creates a new MailProxyInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewMailProxyInfoParamsWithContext(ctx context.Context) *MailProxyInfoParams {
	var ()
	return &MailProxyInfoParams{

		Context: ctx,
	}
}

// NewMailProxyInfoParamsWithHTTPClient creates a new MailProxyInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMailProxyInfoParamsWithHTTPClient(client *http.Client) *MailProxyInfoParams {
	var ()
	return &MailProxyInfoParams{
		HTTPClient: client,
	}
}

/*MailProxyInfoParams contains all the parameters to send to the API endpoint
for the mail proxy info operation typically these are written to a http.Request
*/
type MailProxyInfoParams struct {

	/*XDomainrobotContext*/
	XDomainrobotContext *string
	/*XDomainrobotDemo*/
	XDomainrobotDemo *string
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *string
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotPIN*/
	XDomainrobotPIN *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Domain*/
	Domain string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the mail proxy info params
func (o *MailProxyInfoParams) WithTimeout(timeout time.Duration) *MailProxyInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mail proxy info params
func (o *MailProxyInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mail proxy info params
func (o *MailProxyInfoParams) WithContext(ctx context.Context) *MailProxyInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mail proxy info params
func (o *MailProxyInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mail proxy info params
func (o *MailProxyInfoParams) WithHTTPClient(client *http.Client) *MailProxyInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mail proxy info params
func (o *MailProxyInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotContext adds the xDomainrobotContext to the mail proxy info params
func (o *MailProxyInfoParams) WithXDomainrobotContext(xDomainrobotContext *string) *MailProxyInfoParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the mail proxy info params
func (o *MailProxyInfoParams) SetXDomainrobotContext(xDomainrobotContext *string) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the mail proxy info params
func (o *MailProxyInfoParams) WithXDomainrobotDemo(xDomainrobotDemo *string) *MailProxyInfoParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the mail proxy info params
func (o *MailProxyInfoParams) SetXDomainrobotDemo(xDomainrobotDemo *string) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the mail proxy info params
func (o *MailProxyInfoParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) *MailProxyInfoParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the mail proxy info params
func (o *MailProxyInfoParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *string) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the mail proxy info params
func (o *MailProxyInfoParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *MailProxyInfoParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the mail proxy info params
func (o *MailProxyInfoParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotPIN adds the xDomainrobotPIN to the mail proxy info params
func (o *MailProxyInfoParams) WithXDomainrobotPIN(xDomainrobotPIN *string) *MailProxyInfoParams {
	o.SetXDomainrobotPIN(xDomainrobotPIN)
	return o
}

// SetXDomainrobotPIN adds the xDomainrobotPIN to the mail proxy info params
func (o *MailProxyInfoParams) SetXDomainrobotPIN(xDomainrobotPIN *string) {
	o.XDomainrobotPIN = xDomainrobotPIN
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the mail proxy info params
func (o *MailProxyInfoParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *MailProxyInfoParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the mail proxy info params
func (o *MailProxyInfoParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the mail proxy info params
func (o *MailProxyInfoParams) WithXDomainrobotWS(xDomainrobotWS *string) *MailProxyInfoParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the mail proxy info params
func (o *MailProxyInfoParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithDomain adds the domain to the mail proxy info params
func (o *MailProxyInfoParams) WithDomain(domain string) *MailProxyInfoParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the mail proxy info params
func (o *MailProxyInfoParams) SetDomain(domain string) {
	o.Domain = domain
}

// WriteToRequest writes these params to a swagger request
func (o *MailProxyInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", *o.XDomainrobotContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", *o.XDomainrobotDemo); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", *o.XDomainrobotOwnerContext); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotPIN != nil {

		// header param X-Domainrobot-PIN
		if err := r.SetHeaderParam("X-Domainrobot-PIN", *o.XDomainrobotPIN); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	// path param domain
	if err := r.SetPathParam("domain", o.Domain); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
