// Code generated by go-swagger; DO NOT EDIT.

package document_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/NectGmbH/autodns/models"
)

// DocumentInfoWithAliasReader is a Reader for the DocumentInfoWithAlias structure.
type DocumentInfoWithAliasReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DocumentInfoWithAliasReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDocumentInfoWithAliasOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDocumentInfoWithAliasOK creates a DocumentInfoWithAliasOK with default headers values
func NewDocumentInfoWithAliasOK() *DocumentInfoWithAliasOK {
	return &DocumentInfoWithAliasOK{}
}

/*DocumentInfoWithAliasOK handles this case with default header values.

successful operation
*/
type DocumentInfoWithAliasOK struct {
	Payload *models.JSONResponseDataBasicDocument
}

func (o *DocumentInfoWithAliasOK) Error() string {
	return fmt.Sprintf("[GET /document/{alias}][%d] documentInfoWithAliasOK  %+v", 200, o.Payload)
}

func (o *DocumentInfoWithAliasOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataBasicDocument)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
