// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// HkIndustryTypeConstants hk industry type constants
// swagger:model HkIndustryTypeConstants
type HkIndustryTypeConstants string

const (

	// HkIndustryTypeConstantsX0 captures enum value "_0"
	HkIndustryTypeConstantsX0 HkIndustryTypeConstants = "_0"

	// HkIndustryTypeConstantsX4160 captures enum value "_4160"
	HkIndustryTypeConstantsX4160 HkIndustryTypeConstants = "_4160"

	// HkIndustryTypeConstantsX4224 captures enum value "_4224"
	HkIndustryTypeConstantsX4224 HkIndustryTypeConstants = "_4224"

	// HkIndustryTypeConstantsX4288 captures enum value "_4288"
	HkIndustryTypeConstantsX4288 HkIndustryTypeConstants = "_4288"

	// HkIndustryTypeConstantsX4352 captures enum value "_4352"
	HkIndustryTypeConstantsX4352 HkIndustryTypeConstants = "_4352"

	// HkIndustryTypeConstantsX4416 captures enum value "_4416"
	HkIndustryTypeConstantsX4416 HkIndustryTypeConstants = "_4416"

	// HkIndustryTypeConstantsX8256 captures enum value "_8256"
	HkIndustryTypeConstantsX8256 HkIndustryTypeConstants = "_8256"

	// HkIndustryTypeConstantsX8320 captures enum value "_8320"
	HkIndustryTypeConstantsX8320 HkIndustryTypeConstants = "_8320"

	// HkIndustryTypeConstantsX8384 captures enum value "_8384"
	HkIndustryTypeConstantsX8384 HkIndustryTypeConstants = "_8384"

	// HkIndustryTypeConstantsX8448 captures enum value "_8448"
	HkIndustryTypeConstantsX8448 HkIndustryTypeConstants = "_8448"

	// HkIndustryTypeConstantsX8512 captures enum value "_8512"
	HkIndustryTypeConstantsX8512 HkIndustryTypeConstants = "_8512"

	// HkIndustryTypeConstantsX12352 captures enum value "_12352"
	HkIndustryTypeConstantsX12352 HkIndustryTypeConstants = "_12352"

	// HkIndustryTypeConstantsX12416 captures enum value "_12416"
	HkIndustryTypeConstantsX12416 HkIndustryTypeConstants = "_12416"

	// HkIndustryTypeConstantsX16448 captures enum value "_16448"
	HkIndustryTypeConstantsX16448 HkIndustryTypeConstants = "_16448"

	// HkIndustryTypeConstantsX16512 captures enum value "_16512"
	HkIndustryTypeConstantsX16512 HkIndustryTypeConstants = "_16512"

	// HkIndustryTypeConstantsX16576 captures enum value "_16576"
	HkIndustryTypeConstantsX16576 HkIndustryTypeConstants = "_16576"

	// HkIndustryTypeConstantsX16640 captures enum value "_16640"
	HkIndustryTypeConstantsX16640 HkIndustryTypeConstants = "_16640"

	// HkIndustryTypeConstantsX16704 captures enum value "_16704"
	HkIndustryTypeConstantsX16704 HkIndustryTypeConstants = "_16704"

	// HkIndustryTypeConstantsX16768 captures enum value "_16768"
	HkIndustryTypeConstantsX16768 HkIndustryTypeConstants = "_16768"

	// HkIndustryTypeConstantsX16832 captures enum value "_16832"
	HkIndustryTypeConstantsX16832 HkIndustryTypeConstants = "_16832"

	// HkIndustryTypeConstantsX20544 captures enum value "_20544"
	HkIndustryTypeConstantsX20544 HkIndustryTypeConstants = "_20544"

	// HkIndustryTypeConstantsX20608 captures enum value "_20608"
	HkIndustryTypeConstantsX20608 HkIndustryTypeConstants = "_20608"

	// HkIndustryTypeConstantsX20672 captures enum value "_20672"
	HkIndustryTypeConstantsX20672 HkIndustryTypeConstants = "_20672"

	// HkIndustryTypeConstantsX20736 captures enum value "_20736"
	HkIndustryTypeConstantsX20736 HkIndustryTypeConstants = "_20736"

	// HkIndustryTypeConstantsX20800 captures enum value "_20800"
	HkIndustryTypeConstantsX20800 HkIndustryTypeConstants = "_20800"

	// HkIndustryTypeConstantsX20864 captures enum value "_20864"
	HkIndustryTypeConstantsX20864 HkIndustryTypeConstants = "_20864"

	// HkIndustryTypeConstantsX20928 captures enum value "_20928"
	HkIndustryTypeConstantsX20928 HkIndustryTypeConstants = "_20928"

	// HkIndustryTypeConstantsX24640 captures enum value "_24640"
	HkIndustryTypeConstantsX24640 HkIndustryTypeConstants = "_24640"

	// HkIndustryTypeConstantsX24704 captures enum value "_24704"
	HkIndustryTypeConstantsX24704 HkIndustryTypeConstants = "_24704"

	// HkIndustryTypeConstantsX24768 captures enum value "_24768"
	HkIndustryTypeConstantsX24768 HkIndustryTypeConstants = "_24768"

	// HkIndustryTypeConstantsX28736 captures enum value "_28736"
	HkIndustryTypeConstantsX28736 HkIndustryTypeConstants = "_28736"

	// HkIndustryTypeConstantsX28800 captures enum value "_28800"
	HkIndustryTypeConstantsX28800 HkIndustryTypeConstants = "_28800"

	// HkIndustryTypeConstantsX28864 captures enum value "_28864"
	HkIndustryTypeConstantsX28864 HkIndustryTypeConstants = "_28864"

	// HkIndustryTypeConstantsX28928 captures enum value "_28928"
	HkIndustryTypeConstantsX28928 HkIndustryTypeConstants = "_28928"

	// HkIndustryTypeConstantsX28992 captures enum value "_28992"
	HkIndustryTypeConstantsX28992 HkIndustryTypeConstants = "_28992"

	// HkIndustryTypeConstantsX29056 captures enum value "_29056"
	HkIndustryTypeConstantsX29056 HkIndustryTypeConstants = "_29056"

	// HkIndustryTypeConstantsX29120 captures enum value "_29120"
	HkIndustryTypeConstantsX29120 HkIndustryTypeConstants = "_29120"

	// HkIndustryTypeConstantsX070800 captures enum value "_070800"
	HkIndustryTypeConstantsX070800 HkIndustryTypeConstants = "_070800"

	// HkIndustryTypeConstantsX070900 captures enum value "_070900"
	HkIndustryTypeConstantsX070900 HkIndustryTypeConstants = "_070900"

	// HkIndustryTypeConstantsX080100 captures enum value "_080100"
	HkIndustryTypeConstantsX080100 HkIndustryTypeConstants = "_080100"

	// HkIndustryTypeConstantsX080200 captures enum value "_080200"
	HkIndustryTypeConstantsX080200 HkIndustryTypeConstants = "_080200"

	// HkIndustryTypeConstantsX080300 captures enum value "_080300"
	HkIndustryTypeConstantsX080300 HkIndustryTypeConstants = "_080300"

	// HkIndustryTypeConstantsX080400 captures enum value "_080400"
	HkIndustryTypeConstantsX080400 HkIndustryTypeConstants = "_080400"

	// HkIndustryTypeConstantsX080500 captures enum value "_080500"
	HkIndustryTypeConstantsX080500 HkIndustryTypeConstants = "_080500"

	// HkIndustryTypeConstantsX080600 captures enum value "_080600"
	HkIndustryTypeConstantsX080600 HkIndustryTypeConstants = "_080600"

	// HkIndustryTypeConstantsX080700 captures enum value "_080700"
	HkIndustryTypeConstantsX080700 HkIndustryTypeConstants = "_080700"

	// HkIndustryTypeConstantsX080800 captures enum value "_080800"
	HkIndustryTypeConstantsX080800 HkIndustryTypeConstants = "_080800"

	// HkIndustryTypeConstantsX080900 captures enum value "_080900"
	HkIndustryTypeConstantsX080900 HkIndustryTypeConstants = "_080900"

	// HkIndustryTypeConstantsX081000 captures enum value "_081000"
	HkIndustryTypeConstantsX081000 HkIndustryTypeConstants = "_081000"

	// HkIndustryTypeConstantsX081100 captures enum value "_081100"
	HkIndustryTypeConstantsX081100 HkIndustryTypeConstants = "_081100"

	// HkIndustryTypeConstantsX090100 captures enum value "_090100"
	HkIndustryTypeConstantsX090100 HkIndustryTypeConstants = "_090100"

	// HkIndustryTypeConstantsX090200 captures enum value "_090200"
	HkIndustryTypeConstantsX090200 HkIndustryTypeConstants = "_090200"

	// HkIndustryTypeConstantsX090300 captures enum value "_090300"
	HkIndustryTypeConstantsX090300 HkIndustryTypeConstants = "_090300"

	// HkIndustryTypeConstantsX090400 captures enum value "_090400"
	HkIndustryTypeConstantsX090400 HkIndustryTypeConstants = "_090400"

	// HkIndustryTypeConstantsX090500 captures enum value "_090500"
	HkIndustryTypeConstantsX090500 HkIndustryTypeConstants = "_090500"

	// HkIndustryTypeConstantsX100100 captures enum value "_100100"
	HkIndustryTypeConstantsX100100 HkIndustryTypeConstants = "_100100"

	// HkIndustryTypeConstantsX100200 captures enum value "_100200"
	HkIndustryTypeConstantsX100200 HkIndustryTypeConstants = "_100200"

	// HkIndustryTypeConstantsX100300 captures enum value "_100300"
	HkIndustryTypeConstantsX100300 HkIndustryTypeConstants = "_100300"

	// HkIndustryTypeConstantsX100400 captures enum value "_100400"
	HkIndustryTypeConstantsX100400 HkIndustryTypeConstants = "_100400"

	// HkIndustryTypeConstantsX100500 captures enum value "_100500"
	HkIndustryTypeConstantsX100500 HkIndustryTypeConstants = "_100500"

	// HkIndustryTypeConstantsX110100 captures enum value "_110100"
	HkIndustryTypeConstantsX110100 HkIndustryTypeConstants = "_110100"

	// HkIndustryTypeConstantsX110200 captures enum value "_110200"
	HkIndustryTypeConstantsX110200 HkIndustryTypeConstants = "_110200"

	// HkIndustryTypeConstantsX110300 captures enum value "_110300"
	HkIndustryTypeConstantsX110300 HkIndustryTypeConstants = "_110300"

	// HkIndustryTypeConstantsX110400 captures enum value "_110400"
	HkIndustryTypeConstantsX110400 HkIndustryTypeConstants = "_110400"

	// HkIndustryTypeConstantsX110500 captures enum value "_110500"
	HkIndustryTypeConstantsX110500 HkIndustryTypeConstants = "_110500"

	// HkIndustryTypeConstantsX110600 captures enum value "_110600"
	HkIndustryTypeConstantsX110600 HkIndustryTypeConstants = "_110600"

	// HkIndustryTypeConstantsX120100 captures enum value "_120100"
	HkIndustryTypeConstantsX120100 HkIndustryTypeConstants = "_120100"

	// HkIndustryTypeConstantsX120200 captures enum value "_120200"
	HkIndustryTypeConstantsX120200 HkIndustryTypeConstants = "_120200"

	// HkIndustryTypeConstantsX120300 captures enum value "_120300"
	HkIndustryTypeConstantsX120300 HkIndustryTypeConstants = "_120300"

	// HkIndustryTypeConstantsX120400 captures enum value "_120400"
	HkIndustryTypeConstantsX120400 HkIndustryTypeConstants = "_120400"

	// HkIndustryTypeConstantsX120500 captures enum value "_120500"
	HkIndustryTypeConstantsX120500 HkIndustryTypeConstants = "_120500"

	// HkIndustryTypeConstantsX120600 captures enum value "_120600"
	HkIndustryTypeConstantsX120600 HkIndustryTypeConstants = "_120600"

	// HkIndustryTypeConstantsX120700 captures enum value "_120700"
	HkIndustryTypeConstantsX120700 HkIndustryTypeConstants = "_120700"

	// HkIndustryTypeConstantsX120800 captures enum value "_120800"
	HkIndustryTypeConstantsX120800 HkIndustryTypeConstants = "_120800"

	// HkIndustryTypeConstantsX120900 captures enum value "_120900"
	HkIndustryTypeConstantsX120900 HkIndustryTypeConstants = "_120900"

	// HkIndustryTypeConstantsX130100 captures enum value "_130100"
	HkIndustryTypeConstantsX130100 HkIndustryTypeConstants = "_130100"

	// HkIndustryTypeConstantsX130200 captures enum value "_130200"
	HkIndustryTypeConstantsX130200 HkIndustryTypeConstants = "_130200"

	// HkIndustryTypeConstantsX130300 captures enum value "_130300"
	HkIndustryTypeConstantsX130300 HkIndustryTypeConstants = "_130300"

	// HkIndustryTypeConstantsX130400 captures enum value "_130400"
	HkIndustryTypeConstantsX130400 HkIndustryTypeConstants = "_130400"

	// HkIndustryTypeConstantsX130500 captures enum value "_130500"
	HkIndustryTypeConstantsX130500 HkIndustryTypeConstants = "_130500"

	// HkIndustryTypeConstantsX130600 captures enum value "_130600"
	HkIndustryTypeConstantsX130600 HkIndustryTypeConstants = "_130600"

	// HkIndustryTypeConstantsX130700 captures enum value "_130700"
	HkIndustryTypeConstantsX130700 HkIndustryTypeConstants = "_130700"

	// HkIndustryTypeConstantsX130800 captures enum value "_130800"
	HkIndustryTypeConstantsX130800 HkIndustryTypeConstants = "_130800"

	// HkIndustryTypeConstantsX140101 captures enum value "_140101"
	HkIndustryTypeConstantsX140101 HkIndustryTypeConstants = "_140101"

	// HkIndustryTypeConstantsX140102 captures enum value "_140102"
	HkIndustryTypeConstantsX140102 HkIndustryTypeConstants = "_140102"

	// HkIndustryTypeConstantsX140103 captures enum value "_140103"
	HkIndustryTypeConstantsX140103 HkIndustryTypeConstants = "_140103"

	// HkIndustryTypeConstantsX140200 captures enum value "_140200"
	HkIndustryTypeConstantsX140200 HkIndustryTypeConstants = "_140200"

	// HkIndustryTypeConstantsX140300 captures enum value "_140300"
	HkIndustryTypeConstantsX140300 HkIndustryTypeConstants = "_140300"

	// HkIndustryTypeConstantsX140400 captures enum value "_140400"
	HkIndustryTypeConstantsX140400 HkIndustryTypeConstants = "_140400"

	// HkIndustryTypeConstantsX140500 captures enum value "_140500"
	HkIndustryTypeConstantsX140500 HkIndustryTypeConstants = "_140500"

	// HkIndustryTypeConstantsX140600 captures enum value "_140600"
	HkIndustryTypeConstantsX140600 HkIndustryTypeConstants = "_140600"

	// HkIndustryTypeConstantsX140700 captures enum value "_140700"
	HkIndustryTypeConstantsX140700 HkIndustryTypeConstants = "_140700"
)

// for schema
var hkIndustryTypeConstantsEnum []interface{}

func init() {
	var res []HkIndustryTypeConstants
	if err := json.Unmarshal([]byte(`["_0","_4160","_4224","_4288","_4352","_4416","_8256","_8320","_8384","_8448","_8512","_12352","_12416","_16448","_16512","_16576","_16640","_16704","_16768","_16832","_20544","_20608","_20672","_20736","_20800","_20864","_20928","_24640","_24704","_24768","_28736","_28800","_28864","_28928","_28992","_29056","_29120","_070800","_070900","_080100","_080200","_080300","_080400","_080500","_080600","_080700","_080800","_080900","_081000","_081100","_090100","_090200","_090300","_090400","_090500","_100100","_100200","_100300","_100400","_100500","_110100","_110200","_110300","_110400","_110500","_110600","_120100","_120200","_120300","_120400","_120500","_120600","_120700","_120800","_120900","_130100","_130200","_130300","_130400","_130500","_130600","_130700","_130800","_140101","_140102","_140103","_140200","_140300","_140400","_140500","_140600","_140700"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hkIndustryTypeConstantsEnum = append(hkIndustryTypeConstantsEnum, v)
	}
}

func (m HkIndustryTypeConstants) validateHkIndustryTypeConstantsEnum(path, location string, value HkIndustryTypeConstants) error {
	if err := validate.Enum(path, location, value, hkIndustryTypeConstantsEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this hk industry type constants
func (m HkIndustryTypeConstants) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHkIndustryTypeConstantsEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
