// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Id4MeIdentity id4 me identity
// swagger:model Id4MeIdentity
type Id4MeIdentity struct {

	// Additional information
	Addons Configuration `json:"addons,omitempty"`

	// The ID4ME agent
	// Required: true
	Agent *Id4MeAgent `json:"agent"`

	// The created date.
	// Format: date-time
	Created strfmt.DateTime `json:"created,omitempty"`

	// The initial claims
	InitialClaims *InitialClaims `json:"initialClaims,omitempty"`

	// The language.
	// Required: true
	Language *string `json:"language"`

	// The generated magic link
	MagicLink string `json:"magicLink,omitempty"`

	// Fully qualified domain name
	Name string `json:"name,omitempty"`

	// The owner of the object.
	Owner *BasicUser `json:"owner,omitempty"`

	// DNS text records
	Record []string `json:"record"`

	// status
	Status IdentityStatus `json:"status,omitempty"`

	// The updated date.
	// Format: date-time
	Updated strfmt.DateTime `json:"updated,omitempty"`

	// The updater of the object.
	Updater *BasicUser `json:"updater,omitempty"`

	// Expiration of verification
	// Format: date-time
	VerifyExpire strfmt.DateTime `json:"verifyExpire,omitempty"`
}

// Validate validates this id4 me identity
func (m *Id4MeIdentity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAgent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInitialClaims(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLanguage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwner(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdater(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVerifyExpire(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Id4MeIdentity) validateAgent(formats strfmt.Registry) error {

	if err := validate.Required("agent", "body", m.Agent); err != nil {
		return err
	}

	if m.Agent != nil {
		if err := m.Agent.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("agent")
			}
			return err
		}
	}

	return nil
}

func (m *Id4MeIdentity) validateCreated(formats strfmt.Registry) error {

	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Id4MeIdentity) validateInitialClaims(formats strfmt.Registry) error {

	if swag.IsZero(m.InitialClaims) { // not required
		return nil
	}

	if m.InitialClaims != nil {
		if err := m.InitialClaims.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("initialClaims")
			}
			return err
		}
	}

	return nil
}

func (m *Id4MeIdentity) validateLanguage(formats strfmt.Registry) error {

	if err := validate.Required("language", "body", m.Language); err != nil {
		return err
	}

	return nil
}

func (m *Id4MeIdentity) validateOwner(formats strfmt.Registry) error {

	if swag.IsZero(m.Owner) { // not required
		return nil
	}

	if m.Owner != nil {
		if err := m.Owner.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("owner")
			}
			return err
		}
	}

	return nil
}

func (m *Id4MeIdentity) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		}
		return err
	}

	return nil
}

func (m *Id4MeIdentity) validateUpdated(formats strfmt.Registry) error {

	if swag.IsZero(m.Updated) { // not required
		return nil
	}

	if err := validate.FormatOf("updated", "body", "date-time", m.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Id4MeIdentity) validateUpdater(formats strfmt.Registry) error {

	if swag.IsZero(m.Updater) { // not required
		return nil
	}

	if m.Updater != nil {
		if err := m.Updater.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updater")
			}
			return err
		}
	}

	return nil
}

func (m *Id4MeIdentity) validateVerifyExpire(formats strfmt.Registry) error {

	if swag.IsZero(m.VerifyExpire) { // not required
		return nil
	}

	if err := validate.FormatOf("verifyExpire", "body", "date-time", m.VerifyExpire.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Id4MeIdentity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Id4MeIdentity) UnmarshalBinary(b []byte) error {
	var res Id4MeIdentity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
